spring.application.name=PMS-Pharmacy

spring.datasource.url=jdbc:sqlite:example_db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.port=8080
logging.level.org.springframework=INFO
logging.level.com.pharmacy=DEBUG
